
tasks:
  - name: Setup Java
    init: |
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      sdk version
      echo "$AWS_PEM_KEY" > ~/.ssh/aws-key.pem
      chmod 600 ~/.ssh/aws-key.pem
      chmod 600 ~/.ssh/aws-key.pem
    command: |
      sdk install java 21.0.4-tem -y
      sdk default java 21.0.4-tem
      java -version
      # Start SSH tunnel (only if RDS is private)
      ssh -i ~/.ssh/aws-key.pem -o StrictHostKeyChecking=no \
        -L 3306:${DB_HOST}:${DB_PORT} ubuntu@3.223.195.172 -N 
      

